# Generated by Django 5.0.3 on 2024-03-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_autor', models.CharField(max_length=30)),
                ('resume', models.CharField(max_length=500)),
                ('date_born', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_book', models.CharField(max_length=30)),
                ('name_book', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('categories', models.CharField(choices=[('A', 'Drama'), ('B', 'Romance'), ('C', 'Ficção')], default='B', max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='datacontrol.autor')),
            ],
        ),
    ]
